name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm i

      - name: Run build
        run: npm run build
        env:
          VITE_API_URL: ${{secrets.VITE_API_URL}}

      - name: Create.env file
        run: echo "VITE_API_URL=${{secrets.VITE_API_URL}}" >> .env.local

      - name: Upload to AWS
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-3"
          SOURCE_DIR: "build"
